name: SimCraft
main: com.antgaming.simcraft.SimCraft
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: 0.1
description: Provides additional events to the server
database: true
depend: [Vault]
authors: [Engeltj]
commands:
  blah:
    description: Placeholder